apiVersion: v2
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
- alias: ff-admin-server
  condition: ff-admin-server.enabled
  name: ff-server
  repository: file://../ff-server
  version: 0.1.0
- alias: ff-client-server
  condition: ff-client-server.enabled
  name: ff-server
  repository: file://../ff-server
  version: 0.1.0
- alias: ff-metrics-server
  condition: ff-metrics-server.enabled
  name: ff-server
  repository: file://../ff-server
  version: 0.1.0
- alias: ff-psql-migrations
  condition: ff-psql-migrations.enabled
  name: ff-db-migrations
  repository: file://../ff-db-migrations
  version: 0.1.0
- alias: ff-timescale-migrations
  condition: ff-timescale-migrations.enabled
  name: ff-db-migrations
  repository: file://../ff-db-migrations
  version: 0.1.0
description: A Helm chart for Kubernetes
name: ff-service
type: application
version: 1.1200.0
