apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{- $local := .Values.fileLogging }}
  {{- $global := .Values.global.fileLogging }}
  {{- $enabled := or (and $local $local.enabled) (and $global $global.enabled) }}
  FILE_LOGGING_ENABLED: "{{ ternary "true" "false" $enabled }}"
  {{- if .Values.global.mongoSSL }}
  MONGO_SSL_CONFIG: "true"
  MONGO_SSL_CA_TRUST_STORE_PATH: /opt/harness/keystore.jks
  MONGO_SSL_CA_TRUST_STORE_PASSWORD: password
  {{- end }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- include "harnesscommon.secretsLoader.configContent" (dict "ctx" $ "databaseSecrets" (list 
    (dict "dbtype" "mongo" "usernamesecrets" (list "GATEWAY_MONGO_USER") "passwordsecrets" (list "GATEWAY_MONGO_PASSWORD"))
    (dict "dbtype" "redis" "usernamesecrets" (list "REDIS_USERNAME") "passwordsecrets" (list "REDIS_PASSWORD"))
  )) | nindent 2}}
