apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-control.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{- $resourceGroupClient := "" }}
  {{- if .Values.resourceGroupServiceEnabled }}
  {{- $resourceGroupClient = "http://access-control:9006/api/"}}
  {{- else }}
  {{- $resourceGroupClient = "http://platform-service:9005/api/"}}
  {{- end }}
  RESOURCE_GROUP_CLIENT_BASE_URL: {{ $resourceGroupClient | quote }}
  CODE_SERVICE_SECRET: {{ .Values.codeCreateSecret.CODE_SERVICE_SECRET | quote }}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  # Additional configs
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- include "harnesscommon.monitoring.config" . | nindent 2 }}
  {{- include "harnesscommon.logging.setFileLogging" . | nindent 2 }}
  {{- include "harnesscommon.secretsLoader.configContent" (dict "ctx" $ "databaseSecrets" (list 
    (dict "dbtype" "mongo" "usernamesecrets" (list "MONGODB_USER" "RESOURCEGROUPS_MONGO_USER") "passwordsecrets" (list "MONGODB_PASSWORD" "RESOURCEGROUPS_MONGO_PASSWORD"))
    (dict "dbtype" "redis" "usernamesecrets" (list "LOCK_CONFIG_REDIS_USERNAME" "EVENTS_FRAMEWORK_REDIS_USERNAME" "EVENTS_CONFIG_REDIS_USERNAME") "passwordsecrets" (list "LOCK_CONFIG_REDIS_PASSWORD" "EVENTS_FRAMEWORK_REDIS_PASSWORD" "EVENTS_CONFIG_REDIS_PASSWORD"))
    (dict "dbtype" "postgres" "usernamesecrets" (list "SPICEDB_POSTGRES_USER") "passwordsecrets" (list "SPICEDB_POSTGRES_PASSWORD"))
  )) | nindent 2}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-control.name" . }}-spicedb
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.spicedb.config "context" $) | nindent 2}}