apiVersion: v1
kind: Service
metadata:
  name: {{ include "ff-server.name" . }}
  labels:
    {{- include "ff-server.labels" . | nindent 4 }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: http
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.targetport}}
  {{- if .Values.service.grpcEnabled }}
  - name: grpc
    port: {{.Values.service.grpcport}}
    protocol: TCP
    targetPort: {{.Values.service.targetgrpcport}}
  {{- end }}
  selector:
    {{- include "ff-server.selectorLabels" . | nindent 4 }}
