# Default values for next-gen-ui
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  autoscaling:
    enabled: false
  pdb:
    create: false
  kubeVersion: ''
  loadbalancerURL: ''
  imagePullSecrets: []
  cg:
    enabled: false
  commonLabels: {}
  commonAnnotations: {}
  externalSecretsLoader:
    enabled: false
    provider: 'vault'
    image:
      repository: 'repo/image'
      tag: 'tag'
      pullPolicy: 'IfNotPresent'
    vault:
      address: ''
      engine: ''
      basePath: ''
      auth:
        method: 'token'
        # For Token auth:
        token: 'vault-token'
        # For AppRole:
        roleId: ''
        secretId: ''
        # For Kubernetes auth:
        role: ''
    databases:
      mongo:
        useDatabaseSecretsEngine: false
        engine: ''
        overridePath: ''
        databaseRole: ''
      redis:
        useDatabaseSecretsEngine: false
        engine: ''
        overridePath: ''
        databaseRole: ''
      postgres:
        useDatabaseSecretsEngine: false
        engine: ''
        basePath: ''
        databaseRole: ''
      timescaledb:
        useDatabaseSecretsEngine: false
        engine: ''
        basePath: ''
        databaseRole: ''
  ingress:
    disableHostInIngress: false
    pathPrefix: ''
    pathType:
    # -- create ingress objects
    enabled: false
    # -- set ingress object classname
    className: harness
    # -- set host of ingressObjects
    hosts:
      - my-host.example.org
    # -- set tls for ingress objects
    tls:
      enabled: true
      secretName: ''
    # -- add annotations to ingress objects
    objects:
      annotations: {}
  istio:
    # -- create virtualServices objects
    enabled: false
    # -- create gateway and use in virtualservice
    gateway:
      create: false
    # -- if gateway not created, use specified gateway and host
    virtualService:
      gateways:
      hosts:
replicaCount: 1
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
image:
  registry: docker.io
  repository: harnesssecure/nextgenui-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: '1.137.8'
  digest: 'sha256:ca8ec112de8318e51d3c87ade41e9ad61d575cf0e6164de1ce210b476c435115'
  imagePullSecrets: []
waitForInitContainer:
  image:
    registry: docker.io
    repository: harnesssecure/helm-init-container
    pullPolicy: IfNotPresent
    tag: 'latest'
    digest: 'sha256:3e1e82d9f415e823193a5c48f9f782326e985107cf16c91081cbf5ed41249678'
    imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: 'harness-default'
podAnnotations: {}
podLabels: {}
imagePullSecrets: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext:
  runAsUser: 65534
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
probes:
  readinessProbe:
    httpGet:
      path: /health
      port: ng-ui-port
    periodSeconds: 10
    failureThreshold: 5
  livenessProbe:
    httpGet:
      path: /health
      port: ng-ui-port
    periodSeconds: 10
    failureThreshold: 5
  startupProbe:
    httpGet:
      path: /health
      port: ng-ui-port
    periodSeconds: 10
    failureThreshold: 30
service:
  type: ClusterIP
  protocol: TCP
  port: 80
  targetport: 8080
  annotations: {}
ingress:
  annotations: {}
  objects:
    - annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: 'true'
      paths:
        - path: '{{ .Values.global.ingress.pathPrefix }}/ng(/|$)(.*)'
resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 0.2
    memory: 200Mi
autoscaling:
  enabled: false
  targetCPU: ''
  targetMemory: ''
nodeSelector: {}
tolerations: []
affinity: {}
additionalConfigs: {}
# extraVolumes:
# - name: volume-test
#   configMap:
#     name: test-config
#     readOnly: true
extraVolumes: []
# extraVolumeMounts:
#   - name: test-volume-mount
#     mountPath: /opt/harness/config
extraVolumeMounts: []
# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#   preStop:
#     exec:
#       command:

config:
  API_URL: /gateway
  DEPLOYMENT_TYPE: ON_PREM
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: 'true'
  HARNESS_CLUSTER_URL: ''
  SSCA_PATH_PREFIX: /ssca-manager
  FME_SERVER_URL: https://fme-prod.harness.io/
  FME_SERVER_URL_BASE: https://assets.split.io/webconsole
  ATA_ASSETS_PATH: https://app.relicx.ai/micro-frontend
  ATA_API_SERVER_URL: https://app.relicx.ai/api/
  EXPECTED_HOSTNAME: app.harness.io
  INCLUDE_ALL_LICENSE_LIFECYCLE_STAGES: 'false'
  CSP_REPORT_ONLY_MODE: 'true'
  HARNESS_ENABLE_CSP_HEADERS: 'false'
  CSP_BUGSNAG_ENABLED: 'false'
  CSP_CANNY_ENABLED: 'false'
  CSP_GOOGLE_ENABLED: 'false'
  CSP_INTERCOM_ENABLED: 'false'
  CSP_REFINER_ENABLED: 'false'
  CSP_SEGMENT_ENABLED: 'false'
  CSP_SPLIT_ENABLED: 'false'
  CSP_KAPA_ENABLED: 'false'
  CSP_RELICX_ENABLED: 'false'
  CSP_STRIPE_ENABLED: 'false'
  CSP_NEWRELIC_ENABLED: 'false'
  CSP_ZENDESK_ENABLED: 'false'
  CSP_MIXPANEL_ENABLED: 'false'
  CSP_CONTENTFUL_ENABLED: 'false'
  CSP_ATLASSIAN_ENABLED: 'false'
  CSP_GITHUB_ENABLED: 'false'
  CSP_IDP_CUSTOM_PLUGIN_ENABLED: 'false'
  NEWRELIC_LOADER_URL: 'https://js-agent.newrelic.com/nr-loader-spa-current.min.js'
secrets:
  fileSecret: []
  default: {}
  kubernetesSecrets: {}
  secretManagement: {}
rbac:
  rules: []
pdb:
  create: false
progressDeadlineSeconds: 600
terminationGracePeriodSeconds: 30
