apiVersion: v1
kind: Service
metadata:
  name: {{ include "ff-pushpin-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ff-pushpin-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: "7999"
    port: 7999
    protocol: TCP
    targetPort: 7999
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 443
  - name: "5561"
    port: 5561
    protocol: TCP
    targetPort: 5561
  selector:
     {{- include "ff-pushpin-service.selectorLabels" . | nindent 4 }}
