# Default values for ui
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  autoscaling:
    enabled: false
  kubeVersion: ""
  loadbalancerURL: ""
  airgap: false
  imagePullSecrets: []
  commonAnnotations: {}
  commonLabels: {}
  pdb:
    create: false
  externalSecretsLoader:
    enabled: false
    provider: "vault"
    image:
      repository: "repo/image"
      tag: "tag"
      pullPolicy: "IfNotPresent"
    vault:
      address: ""
      engine: ""
      basePath: ""
      auth:
        method: "token"
        # For Token auth:
        token: "vault-token"
        # For AppRole:
        roleId: ""
        secretId: ""
        # For Kubernetes auth:
        role: ""
    databases:
      mongo:
        useDatabaseSecretsEngine: false
        engine: ""
        overridePath: ""
        databaseRole: ""
      redis:
        useDatabaseSecretsEngine: false
        engine: ""
        overridePath: ""
        databaseRole: ""
      postgres:
        useDatabaseSecretsEngine: false
        engine: ""
        basePath: ""
        databaseRole: ""
  ingress:
    enabled: false
    disableHostInIngress: false
    pathPrefix: ""
    pathType: ""
    objects:
      annotations: {}
    className: harness
    tls:
      enabled: false
      secretName: harness-cert
    additionalPaths:
    # - path: abc
    #   pathType: ImplementationSpecific
    #     backend:
    #         service:
    #           name: release-name-ui
    #           port:
    #             number: 80
  istio:
    enabled: false
    gateway:
      create: false
    virtualService:
      gateways:
      hosts:
  waitForInitContainer:
    enabled: true
    image:
      registry: docker.io
      repository: harnesssecure/helm-init-container
      pullPolicy: Always
      tag: "latest"
      digest: "sha256:3e1e82d9f415e823193a5c48f9f782326e985107cf16c91081cbf5ed41249678"
      imagePullSecrets: []
replicaCount: 1
revisionHistoryLimit: 10
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
image:
  registry: docker.io
  repository: harnesssecure/ui-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.36.2"
  digest: "sha256:4aaa05269dd9680245a73e5965d5e5cff86df830664d16b3179bf166de2fc06a"
  imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext:
  runAsUser: 65534
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  annotations: {}
  type: ClusterIP
  port: 80
  targetPort: 8080
virtualService:
  annotations: {}
  objects:
    - name: ui
      pathMatchType: prefix
      pathRewrite: "/"
      paths:
        - path: '{{ .Values.global.istio.virtualService.pathPrefix }}/'
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: false
  targetCPU: 80
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  annotations: {}
  objects:
    - annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"
      paths:
        - path: '{{ .Values.global.ingress.pathPrefix }}/(.*)'
pdb:
  create: false
secrets:
  fileSecret: []
  default: {}
  kubernetesSecrets: {}
  secretManagement: {}
config:
  API_URL: '{{ .Values.global.loadbalancerURL }}/gateway'
  BUILD_NUMBER: '{{ .Values.image.tag }}'
  HARNESS_ENABLE_DRIFT_PLACEHOLDER: "false"
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: "true"
  HARNESS_ENABLE_NEWRELIC_EUM_PLACEHOLDER: "false"
  CDN: "0"
# Additional configurations to be Depercated use config instead which allows
# for templating and overrides.
additionalConfigs: {}
rbac:
  rules: []
probes:
  readinessProbe:
    httpGet:
      path: /health
      port: http-ui
    initialDelaySeconds: 15
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /health
      port: http-ui
    initialDelaySeconds: 100
    periodSeconds: 20
    failureThreshold: 5
terminationGracePeriodSeconds: 15
progressDeadlineSeconds: 600
