apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-discovery-manager.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "service-discovery-manager.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.monitoring.config" . | nindent 2 }}
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{- include "harnesscommon.secretsLoader.configContent" (dict "ctx" $ "databaseSecrets" (list 
    (dict "dbtype" "mongo" "usernamesecrets" (list "MONGO_DB_USERNAME") "passwordsecrets" (list "MONGO_DB_PASSWORD"))
    (dict "dbtype" "redis" "usernamesecrets" (list "REDIS_LOCK_USERNAME" "REDIS_EVENT_USERNAME") "passwordsecrets" (list "REDIS_LOCK_PASSWORD" "REDIS_EVENT_PASSWORD"))
  )) | nindent 2}}
