apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service
  namespace: {{ .Release.Namespace }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}