apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "policy-mgmt.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policy-mgmt.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  APP_ENV: {{ .Release.Namespace | quote }}
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{- include "harnesscommon.secretsLoader.configContent" (dict "ctx" $ "databaseSecrets" (list 
    (dict "dbtype" "redis" "usernamesecrets" (list "APP_EVENTS_FRAMEWORK_REDIS_USERNAME") "passwordsecrets" (list "APP_EVENTS_FRAMEWORK_REDIS_PASSWORD"))
    (dict "dbtype" "postgres" "usernamesecrets" (list "APP_DATABASE_USER") "passwordsecrets" (list "APP_DATABASE_PASSWORD"))
  )) | nindent 2}}
