{{- if eq (include "harnesscommon.secretsLoader.enabled" (dict "ctx" $)) "false" }}
apiVersion: v1
kind: Secret
metadata:
  name: looker-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "looker.generateLookerInternalSecrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: harness-looker-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "looker.generateLookerSecrets" . }}
{{- end }}
