---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chaos-linux-ifs.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    name: {{ include "chaos-linux-ifs.name" . }}
    {{- include "chaos-linux-ifs.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods/exec", "pods", "pods/log"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  {{- if .Values.global.crd.enabled }}
  - apiGroups: ["litmuschaos.io"]
    resources: ["taskdefinitions","linuxchaosexperiments"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chaos-linux-ifs.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    name: {{ include "chaos-linux-ifs.name" . }}
    {{- include "chaos-linux-ifs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chaos-linux-ifs.name" . }}
subjects:
  - kind: ServiceAccount
    name: '{{ include "chaos-linux-ifs.serviceAccountName" . }}'
