apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaos-machine-ifs.name" . }}-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "chaos-machine-ifs.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: chaos-machine-gql-ifs
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetport}}
      protocol: TCP
  selector:
    component: {{ include "chaos-machine-ifs.name" . }}
   {{- include "chaos-machine-ifs.selectorLabels" . | nindent 4 }}
