{{- include "harnesscommon.v1.renderVirtualService" (dict "ctx" $) }}

---
{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "harness-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.virtualService.annotations }}
    {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.virtualService.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  gateways:
    {{- if or (not .Values.global.istio.virtualService.gateways) (.Values.global.istio.gateway.create) }}
    - {{ .Values.global.istio.gateway.namespace | default "istio-system" }}/{{ .Values.global.istio.gateway.name | default "public" }}
    {{- else }}
    {{- range .Values.global.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
    {{- end }}
  hosts:
    {{- range .Values.global.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  tcp:
    - match:
        - port: 9879
      route:
        - destination:
            host: harness-manager
            port:
              number: 9879
{{ end }}
