apiVersion: v1
type: postrenderer/v1
name: harness-listenerset-parentref
version: 0.2.0
runtime: subprocess
runtimeConfig:
  platformCommand:
    - command: ${HELM_PLUGIN_DIR}/listenerset-parentref-post-renderer
