{{- include "harnesscommon.v1.renderIngress" (dict "ctx" $) }}
{{- if .Values.global.ingress.enabled -}}
{{- if not .Values.global.cg.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harness-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "next-gen-ui.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.ingress.objects.annotations }}
  annotations:
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.ingress.objects.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  rules:
    {{- if .Values.global.ingress.disableHostInIngress }}
    - http:
        paths:
          - backend:
              service:
                name: next-gen-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
    {{- else }}
    {{- range .Values.global.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: next-gen-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
    {{- end }}
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}
{{- end }}
